config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "pages#index"

  get "/about", to: "pages#about"

  resources :favorites, only: [:index]

  resources :boards do
    member do
      post :favorite
    end

    resources :posts, shallow: true do
      resources :comments, shallow: true, only: [:create]
    end
  end

  resources :users , only: [:create] do
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end
  #可自行控制頁面
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord

  acts_as_paranoid  

  has_many :posts

  has_many :board_masters
  has_many :users, through: :board_masters

  has_many :favorite_boards
  has_many :favorited_users, through: :favorite_boards, source: :user


  validates :title, presence: true, length:{minimum: 2}


end
 

app/models/board_master.rb
class BoardMaster < ApplicationRecord
  belongs_to :user
  belongs_to :board
end

app/models/favorite_board.rb
class FavoriteBoard < ApplicationRecord
  belongs_to :user
  belongs_to :board
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :serial, uniqueness: true


  belongs_to :board
  belongs_to :user
  has_many :comments
  
  before_save :create_serial

  def display_username
    if user.nil?
      "-"
    else
      user.account
    end
  end
  

  private

  def create_serial
    self.serial = serial_generator(10)
  end
  
  def serial_generator(n)
    [*'a'..'z',*'A'..'Z',*0..9].sample(n).join
  end
  

end

app/models/user.rb
class User < ApplicationRecord
validates :account, :email, presence: true, uniqueness: true
before_create :encrypt_password

has_many :posts 
has_many :board_masters
has_many :boards, through: :board_masters
has_many :comments

has_many :favorite_boards
has_many :favorited_boards, through: :favorite_boards, source: :board

def self.login(options)
  if options[:account] && options[:password]
    find_by(account: options[:account],password: Digest::SHA1.hexdigest("x" + options[:password] + "y")) 
  end
  
end

def toggle_favorite_board(b)
  if favorited_boards.exists?(b.id)
     favorited_boards.destroy(b) 
  else
    favorited_boards<< b
  end
end



private

def encrypt_password
  self.password = bigbang(self.password)
end

def bigbang(string)
  string = "x"+ string + "Y"
  Digest::SHA1.hexdigest(string)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  helper_method :user_signed_in?, :current_user

private
  

def not_found
   render file: '/public/404.html', status: 404,layout: false
end

def user_signed_in?
  current_user != nil
end

def current_user
    @current_user ||= User.find_by(id: session[:user_token])
end

def authenticate_user!
  redirect_to root_path, notice: "請登入會員" if not user_signed_in?
end


end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController


  before_action :find_board, only: [:favorite, :show, :update, :edit , :destroy]

  before_action :authenticate_user!, except: [:index, :show]
 
def index
  @boards = Board.all
end

def favorite
  current_user.toggle_favorite_board (@board)
  redirect_to favorites_path, notice:'ok'
  
end


def show
  @posts = @board.posts.includes(:user)
end

def new
    @board = Board.new
end

def create
  @board = Board.new (board_params)
  if @board.save  
     redirect_to boards_path, notice: "Successfully created a new board" 
  else
    render 'new'
  end
end


def edit
end

def update
  if @board.update(board_params)
     redirect_to boards_path, notice: "updated"
  else
    render :edit
  end
end

def destroy
 @board.destroy
 redirect_to boards_path, notice: "delete" 
end



private

def board_params
  params.require(:board).permit(:title, :intro)
end

def find_board
  @board = Board.find(params[:id])  
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    redirect_to @post
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user: current_user)
  end
  
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

def index
  @boards = current_user.favorited_boards
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_board, only: [:new, :create]
  before_action :authenticate_user!, except:[:show]
  
  def new
    @post = @board.posts.new
  end
  
  def create
     @post = @board.posts.new(post_params) 
    #  看板角度新增文章（少了user_id）
    # @post.user = current_user
    # @post = current_user.pots.new(post_params) 使用者角度新增文章
    if @post.save
    redirect_to @board, notice: "successfully created"      
    else
      render :new
    end
  end  

  def edit
    # @post = Post.find_by(id:params[:id],user: current_user)
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: 'successfully updated'
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.new
    @comments = @post.comments

  end
  
  

  private

  def post_params
    params.require(:post).permit(:title, :content).merge(user: current_user)
  end
  

  def find_board
    @board = Board.find(params[:board_id])

  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_in
    @user = User.new
  end

  def sign_up
    @user = User.new
  end

  def login
      user = User.login(user_params)
      if user
          signed_in_user(user)
          redirect_to root_path, notice: "successfully sign_in"
      else
        redirect_to sign_in_users_path, notice: "please enter correct password"
      end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in_user(@user)
      redirect_to root_path,notice: 'successfully signed_up'
    else
      render :sign_up
    end
  end

  def sign_out
    sign_out_user
    redirect_to root_path, notice: "successfully sign-out"
  end
  

  private 

  def sign_in_user(u)
    session[:user_token] = u.id
  end

  def sign_out_user
    session[:user_token] = nil
  end
  
  def user_params
    params.require(:user).permit(:account, :password, :email)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
  def display_bm(board)
    if board.users.count == 0
      "徵求中"
    else
      board.users.map {|user|user.account}.join("/")
    end
  end  
end

app/helpers/users_helper.rb
module UsersHelper

  
end

app/views/boards/_form.html.erb
<%if board.errors.any?%>
<ul>
  <% board.errors.full_messages.each do |message| %>
  <li><%= message%></li>
  <%end%>
</ul>
<%end%> <%= form_for(board) do |f| %>

<div class="fields">
  <%= f.label :title, "看板名稱" %> <%= f.text_field :title%>
</div>

<div class="fields">
  <%= f.label :intro, "看板說明" %> <%= f.text_area :intro%>
</div>

<%= f.submit "send" %> <% end %>

app/views/boards/edit.html.erb
<h2>編輯看板</h2>

<%= render 'form', board: @board%>

app/views/boards/index.html.erb
<div class="wrap">
  <h1>看版</h1>

  <%=link_to "新增看板", new_board_path %>

  <ul>
    <% @boards.each do |board| %>
    <li>
      <%= link_to board.title, board_path(board)%> 
      <%= link_to "edit",edit_board_path(board)%> 
      <%= link_to "delete" ,board_path(board),method: "delete", data: {confirm: "Are you sure"}%>
    </li>
    <% end %>
  </ul>
</div>

app/views/boards/new.html.erb
<h2>新增看板</h2>

<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<h1>看板 <%= @board.title %>
<%= link_to "我的最愛", favorite_board_path(@board), method:'post'%></h1>

<div>
  [版主: <%= display_bm(@board)%>]
</div>
<%= link_to "New", new_board_post_path(@board)%>
<ul>
  <% @posts.each do |post|%>
  <li>
    <%= post.display_username %>
    <%= post.title%>
    <%= link_to' edit', edit_post_path(post)%>
  </li>
  <%end%>
</ul>

app/views/boards/update.html.erb
<h1> Update </h1>
<%= render 'form' %>

app/views/favorites/index.html.erb
<h1>我的最愛</h1>

<% if @boards.any?%>
<ul>
  <% @boards.each do |board|%>
  <li>
    <%= board.title %>
  </li>
  <% end %>
</ul>
<% else %>
    目前沒有最愛
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PttDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/frontend/navbar'%>
    <%= render 'shared/common/flash'%>
    <%= yield %>
    <%= render 'shared/frontend/footer'%>
  </body>
</html>

app/views/pages/index.html.erb
 <section class="home">
  <div class="menu">
    <ul>
      <li class="list"><%= link_to "(A)nnounce【 精華公佈欄 】", "#" %></li>
      <li class="list"><%= link_to "(F)avorite【 我的最愛 】", "#" %></li>
      <li class="list"><%= link_to "(C)lass【 分組討論區 】", "#" %></li>
      <li class="list"><%= link_to "(M)ail【 私人信件區 】", "#" %></li>
      <li class="list"><%= link_to "(T)alk【 休閒聊天區 】", "#" %></li>
      <li class="list"><%= link_to "(U)ser【 個人設定區 】", "#" %></li>
      <li class="list"><%= link_to "(X)yz【 系統資訊區 】", "#" %></li>
      <li class="list"><%= link_to "(P)lay【 娛樂與休閒 】", "#" %></li>
      <li class="list"><%= link_to "(N)amelist【 編特別名單 】", "#" %></li>
    </ul>
  </div>
</section>

app/views/posts/_form.html.erb
<%= form_with(model: @post, url: board_posts_path(@board), local: true) do |f| %>

<div class="fields">
<%= f.label :title, "看板名稱" %>
<%= f.text_field :title%>
</div>

<div class="fields">
<%= f.label :intro, "看板說明" %>
<%= f.text_area :intro%>
</div>
<%= f.submit %>

<%end%>

app/views/posts/edit.html.erb
<h1>Edit</h1>

<%= form_with(model: @post, local: true) do |f| %>

<div class="fields">
<%= f.label :title, "看板名稱" %>
<%= f.text_field :title%>
</div>

<div class="fields">
<%= f.label :intro, "看板說明" %>
<%= f.text_area :intro%>
</div>
<%= f.submit %>

<%end%>

app/views/posts/new.html.erb
<h1>新貼文</h1>
<%= render 'form'%>

app/views/posts/show.html.erb
<ul>
  <li>
  <span>Author</span>
  <span><%= @post.user.account%></span>
  </li>
  <li>
  <span>看板</span>
  <span><%= @post.board.title%></span>
  </li>
  <li>
  <span>Title</span>
  <span><%= @post.title%></span>
  </li>
  <li>
  <span>Time</span>
  <span><%= @post.created_at%></span>
  </li>
</ul>



<%= form_with (model: @comment, url: post_comments_path(@post))do |form|%>
<%= form.text_field :content %>
<%= form.submit "送出" %>
<% end %>
<hr>
<ul>
<% @comments.each do |comment| %>
  <li><%= comment.content %></li>
<% end %>
</ul>



<h1><%= @post.title %></h1>
<h2><%= @post.content %></h2>

app/views/shared/common/_flash.html.erb
    <%= notice%>

app/views/shared/frontend/_navbar.html.erb
<nav>
  <ul>
    <%if user_signed_in? %>
      <li> <%= current_user.account%> </li>
      <li> <%= link_to "sign_out", sign_out_users_path, method: 'delete',notice: "Are you sre?"%> </li>
    <%else%>
      <li> <%= link_to "sign_in", sign_in_users_path%> </li>    
      <li> <%= link_to "sign_up", sign_up_users_path%> </li>
    <%end%>
  </ul>
</nav>

app/views/users/sign_in.html.erb
<h1>SIGN_IN</h1>

<%= form_for(@user, url: login_users_path) do |f|%>
<div class="fields">
  <%=f.label :account%>
  <%=f.text_field :account, placeholder: "please put your account and email"%>
</div>
<div class="fields">
  <%=f.label :password%>
  <%=f.password_field :password%>
</div>
  <%=f.submit "sign_in"%>

<%end%>

app/views/users/sign_up.html.erb
<div class="wrap">

  <h1>Member sign_up</h1>

  <%= form_for (@user) do |form|%>

    <div class="fields">
      <%= form.label :account, "Account"%>
      <%= form.text_field :account%>
    </div>
    <div class="fields">
      <%= form.label :password, "Password"%>
      <%= form.password_field :password%>
    </div>
    <div class="fields">
      <%= form.label :email, "Email"%>
      <%= form.email_field :email%>
    </div>

    <%= form.submit "submit"%>

  <%end%>
</div>